### ISSUE TITLE
Add Haiku as an operating system supporting RISC-V hardware

### ISSUE THREAD

**Issue by X547** [mikeroyal/RISC-V-Guide#23]
Haiku is a UNIX-like MIT-licensed desktop operating system compatible with BeOS. It use it own kernel and GUI subsystem.

Haiku currently supports various emulators (QEMU, TinyEMU, RVVM (not yet upstreamed)) and real hardware (HiFive Unmatched, VisionFive 2 (not yet upstreamed)).

Information for running Haiku on RISC-V platform: https://www.haiku-os.org/blog/kallisti5/2021-11-07_booting_our_risc-v_images/.

**Comment by mikeroyal** [comment]
Thanks, for the suggestion I'll take a look at it.

**Comment by mikeroyal** [comment]
Okay, a PR has been made to add Haiku.
